{ nixpkgs, pkgs }:
let
  # nixos/modules/services/desktop-managers/gnome.nix
  gnomePkgs = {
    inherit (pkgs)
      gnome-shell
      gnome-session
      mutter
      avahi
      geoclue2
      orca
      adwaita-icon-theme
      gnome-backgrounds
      gnome-bluetooth
      gnome-color-manager
      gnome-control-center
      gnome-tour
      gnome-user-docs
      glib
      gnome-menus
      xdg-user-dirs
      xdg-user-dirs-gtk
      baobab
      decibels
      epiphany
      gnome-text-editor
      gnome-calculator
      gnome-calendar
      gnome-characters
      gnome-clocks
      gnome-console
      gnome-contacts
      gnome-font-viewer
      gnome-logs
      gnome-maps
      gnome-music
      gnome-system-monitor
      gnome-weather
      loupe
      nautilus
      gnome-connections
      simple-scan
      snapshot
      totem
      yelp
      # gnome-software flatpak?
      evince
      file-roller
      geary
      gnome-disk-utility
      seahorse
      sushi
      bash
      zsh
      # games?
      # core-developer-tools?
      ;

    gtk3 = pkgs.gtk3.out;
  };

  # nixos/modules/services/desktop-managers/plasma6.nix
  plasma6Pkgs = {
    inherit (pkgs.kdePackages)
      qtwayland
      qtsvg
      frameworkintegration
      kauth
      kcoreaddons
      kded
      kfilemetadata
      kguiaddons
      kiconthemes
      kimageformats
      qtimageformats
      kio
      kio-admin
      kio-extras
      kio-fuse
      kpackage
      kservice
      kunifiedpush
      kwallet
      kwallet-pam
      kwalletmanager
      plasma-activities
      solid
      phonon-vlc
      kwin
      kscreen
      libkscreen
      kscreenlocker
      kactivitymanagerd
      kde-cli-tools
      kglobalacceld
      kwrited
      baloo
      milou
      kdegraphics-thumbnailers
      polkit-kde-agent-1
      plasma-desktop
      plasma-workspace
      drkonqi
      kde-inotify-survey
      libplasma
      plasma-integration
      kde-gtk-config
      breeze
      breeze-icons
      breeze-gtk
      ocean-sound-theme
      qqc2-breeze-style
      qqc2-desktop-style
      kdeplasma-addons
      kmenuedit
      kinfocenter
      plasma-systemmonitor
      ksystemstats
      libksysguard
      systemsettings
      kcmutils
      ;
    inherit (pkgs)
      hicolor-icon-theme
      xdg-user-dirs
      ;

    # Optional packages
    inherit (pkgs.kdePackages)
      aurorae
      plasma-browser-integration
      plasma-workspace-wallpapers
      konsole
      kwin-x11
      ark
      elisa
      gwenview
      okular
      kate
      khelpcenter
      dolphin
      baloo-widgets
      dolphin-plugins
      spectacle
      ffmpegthumbs
      krdp
      ;
    qttools = pkgs.lib.getBin pkgs.kdePackages.qttools;

    # flatpak?
  };

  systemClosures = pkgs.callPackage ./closures.nix { inherit nixpkgs; };
in
{ }
// gnomePkgs
// plasma6Pkgs
// systemClosures
// {
  inherit (pkgs)
    age
    alsa-firmware
    alsa-utils
    amdgpu_top
    aria2
    asciidoc
    asciinema_3
    aspell
    attic-client
    autoconf
    automake
    bash
    bat
    bcache-tools
    bind
    binutils
    bison
    bluez
    bluez-alsa
    bluez-tools
    bootspec
    btop
    btrfs-progs
    busybox
    bzip2
    cairo
    cargo
    ccrypt
    cifs-utils
    ckbcomp
    clang
    cloud-utils
    clutter
    cmake
    cmus
    cogl
    connman
    corectrl
    coreutils
    coreutils-full
    cryptsetup
    curl
    curlFull
    curlMinimal
    db
    dbus
    dbus-broker
    dconf
    ddrescue
    dejavu_fonts
    direnv
    dmenu
    dns-over-https
    docbook-xsl-ns
    docbook5
    docker
    docker-compose
    dtc
    dumbpipe
    e2fsprogs
    efibootmgr
    exiv2
    expat
    expect
    f2fs-tools
    fakeroot
    fastfetch
    fastfetchMinimal
    fatresize
    feh
    ffmpeg
    file
    firefox
    fish
    flex
    freetype
    fzf
    gatus
    gdb
    getconf
    gettext
    gh
    ghc
    git
    git-absorb
    gixy
    glance
    glibcLocales
    glibcLocalesUtf8
    gmp
    gnupg
    gnutls
    go
    gost
    gparted
    gptfdisk
    graphene
    grml-zsh-config
    grub2_efi
    grub2_light
    gsl
    guile
    hello
    help2man
    htop
    hunspell
    hydra-check
    i2pd
    ibus
    iconnamingutils
    iftop
    inetutils
    inkscape
    iotop
    iotop-c
    iperf3
    isl
    iw
    iwd
    jfsutils
    jq
    lego
    less
    lesspipe
    lib2geom
    libelf
    libffi
    libmpc
    libressl
    librevenge
    libsecret
    libuv
    libxcrypt
    libxml2
    libxslt
    limine
    linux-firmware
    lirc
    llvm
    logrotate
    lshw
    lsof
    lua
    makeInitrdNGTool
    man-pages
    mc
    mdadm
    mdbook
    mesa
    mesa-demos
    meson
    mihomo
    minica
    mkpasswd
    moc
    modemmanager
    mosquitto
    mpc
    mpd
    mpfr
    # mpv
    ms-sys
    mtdutils
    mtools
    mympd
    mypy
    nano
    ncmpcpp
    ncurses
    neofetch
    netbird
    netdata
    networkmanager
    nfs-utils
    nginx
    ninja
    nix
    nix-info
    nix-update
    nixd
    nixfmt
    nixfmt-tree
    nixos-init
    nixos-install-tools
    nixos-option
    nixos-rebuild
    nixos-rebuild-ng
    nixpkgs-review
    nixpkgs-track
    nmap
    nodejs
    nodejs-slim
    npth
    nsncd
    ntfs3g
    nvme-cli
    openexr
    openldap
    openssh
    openssl
    openvpn
    p7zip
    pandoc
    pango
    patchelf
    pciutils
    pcre
    perl
    picom
    pipewire
    pkg-config
    polkit
    prometheus
    prometheus-node-exporter
    protobuf
    pulseaudio
    pulseaudio-ctl
    pulseaudioFull
    python3
    qemu
    qemu_full
    qemu_kvm
    qemu-user
    qemu-utils
    rage
    readline
    remarshal
    ripgrep
    ronn
    ruby
    rustc
    samba
    screen
    sd-switch
    sdparm
    sendme
    shellcheck-minimal
    smartmontools
    socat
    sof-firmware
    speedtest-cli
    sqlite
    squashfs-tools-ng
    squashfsTools
    sshfs
    stdenv
    strace
    strongswan
    sudo
    swig
    swtpm
    sysstat
    systemd
    systemdMinimal
    tailscale
    tcl
    tcp_wrappers
    tcpdump
    telegram-bot-api
    terminus_font
    testdisk
    texinfo
    texinfoInteractive
    time
    tio
    tk
    tmux
    traceroute
    tree
    tshark
    txt2tags
    unbound
    unicode-character-database
    unicode-emoji
    unrar
    unzip
    usbutils
    util-linux
    vaultwarden
    vim
    w3m
    w3m-nox
    wakeonlan
    webkitgtk_4_1
    webkitgtk_6_0
    wget
    which
    whois
    wireguard-tools
    wirelesstools
    wireplumber
    wpa_supplicant
    xorriso
    xz
    zlib
    zram-generator
    zsh
    ;
}
